app = 'mind-zero-five'
primary_region = 'syd'

[build]

[env]
  PORT = '8080'
  MIND_ENABLED = 'true'
  MIND_REPO_DIR = '/data/source'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[mounts]
  source = "mz5_data"
  destination = "/data"

[[vm]]
  memory = '4096'
  cpu_kind = 'shared'
  cpus = 2
